language: php
dist: bionic

notifications:
  email:
    on_success: never
    on_failure: change

git:
    depth: 1

services:
  - mysql

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.1.0

env:
  global:
    - WP_VERSION=latest
  jobs:
    - CUSTOM_CONSTANTS=0
    - CUSTOM_CONSTANTS=1
    - WP_MULTISITE=0
    - WP_MULTISITE=1

jobs:
  include:
    - php: 8.1.0
      env: PHPUNIT_VERSION=9.3

install:
    # flags to pass to install
    - flags="--ansi --prefer-dist --no-interaction --optimize-autoloader --no-progress"
    # install dependencies using system provided composer binary
    - composer install $flags
    - composer require --no-interaction --dev phpunit/phpunit:${PHPUNIT_VERSION:-7.5.0}

before_script:
  # install wp tests infra
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  # print what's installed and where by default
  # - which phpunit && phpunit --version

script: ./vendor/bin/phpunit
